### ISSUE TITLE
ttf字体已经更换，但问题依然存在

### ISSUE THREAD

**Issue by cai620** [Tankzors/Builds#3]
![Screenshot_20210703_151928](https://user-images.githubusercontent.com/86501852/124346615-69857800-dbcf-11eb-845e-c68591a18000.jpg)
![Screenshot_20210703_151910](https://user-images.githubusercontent.com/86501852/124346617-6db19580-dbcf-11eb-9da7-dceb6cad43c3.jpg)
好像不是这样添加的，它直接显示了所有代码

**Comment by RblSb** [comment]
Will check what can i do soon. Please do not make more issues, comment in #1 and use google translate.
